name: greystone
base: core24
version: '1.0.1'
summary: Beginner friendly Minecraft Server manager
description: |
  A beginner friendly web interface to manage, backup, and
  run a Minecraft Java server. The users yearn for the mines!

grade: stable
confinement: strict

apps:
  greystone:
    command: bin/python3 $SNAP/app.py
    daemon: simple
    restart-condition: always
    plugs:
      - network        
      - network-bind   
    environment:
      PYTHONUNBUFFERED: "1"

  launcher:
    command: usr/bin/xdg-open http://localhost:8080
    desktop: snap/gui/launcher.desktop
    plugs:
      - desktop

parts:
  greystone-app:
    plugin: dump
    source: .
    
  greystone-env:
    plugin: python
    source: .
    build-packages:
      - ca-certificates-java
      - default-jre-headless
    python-packages:
      - flask
    stage-packages:
      - openjdk-25-jre-headless
      - xdg-utils
    override-prime: |
      craftctl default
      for cacert in $CRAFT_PRIME/usr/lib/jvm/java-*-openjdk-*/lib/security/cacerts; do
        if [ -L "$cacert" ]; then
          rm "$cacert"
          cp /etc/ssl/certs/java/cacerts "$cacert"
        fi
      done
